### PR TITLE
Hide user Testing pages

### PR DESCRIPTION
**Pull request by junkbot**
This just hides the Testing page from being accessed. Do we want to also disable /testing [which would let them do user tests, but not sure if anyone is going to try this...]?

### CODE REVIEW

**Comment by bgbnbigben** [comment]
....why? We don't want to allow people to do user tests in the AIO?

**Comment by bgbnbigben** [comment]
Huh, so somehow the most compelling argument is "The IOI removed it". I would have thought it _particularly_ useful for first-timers, but yolo.

@KKMahogany might be worth knowing for you / your PR!

**Comment by bgbnbigben** [comment]
If that's the case I'd probably disable /testing, I'm sure we'll get someone navigating to there via a hand-crafted url and thinking themselves l33t h4x0rs or something

**Comment by KKMahogany** [comment]
My PR?
Does that mean I shouldn't push my changes wrt to the user tests?

**Comment by bgbnbigben** [comment]
I guess it means we don't care about user tests, yeah.

**Comment by bgbnbigben** [comment]
Uhhhhhhhh.

Is there a reason you didn't just comment out the testing URLs at https://github.com/aioc/cms/blob/aioc-v1.2/cms/server/ContestWebServer.py#L2047 ?

**Pull request merged**
